const { SlashCommandBuilder } = require('@discordjs/builders')
const { MessageEmbed } = require('discord.js')
const malScraper = require('mal-scraper')

module.exports = {
    data: new SlashCommandBuilder()
        .setName('anime')
        .setDescription('Fetches data about an anime you search for')
        .addStringOption(option => option.setName('query').setDescription('Name of the anime to search').setRequired(true)),
    async execute(interaction) {
        let search = interaction.options.getString('query')
        await malScraper.getInfoFromName(search)
            .then((data) => {
                const malEmbed = new MessageEmbed()
                    .setTitle(`My Anime List search result for ${search}`)
                    .setThumbnail(data.picture)
                    .setColor('RANDOM')
                    .addField('Premiered', `\`${data.premiered}\``, true)
                    .addField('Broadcast', `\`${data.broadcast}\``, true)
                    .addField('Genres', `\`${data.genres}\``, true)
                    .addField('English Title', `\`${data.englishTitle}\``, true)
                    .addField('Japanese Title', `\`${data.japaneseTitle}\``, true)
                    .addField('Type', `\`${data.type}\``, true)
                    .addField('Episodes', `\`${data.episodes}\``, true)
                    .addField('Rating', `\`${data.rating}\``, true)
                    .addField('Aired', `\`${data.aired}\``, true)
                    .addField('Score', `\`${data.score}\``, true)
                    .addField('Favorite', `\`${data.favorites}\``, true)
                    .addField('Ranked', `\`${data.ranked}\``, true)
                    .addField('Duration', `\`${data.duration}\``, true)
                    .addField('Studios', `\`${data.studios}\``, true)
                    .addField('Popularity', `\`${data.popularity}\``, true)
                    .addField('Members', `\`${data.members}\``, true)
                    .addField('Score Stats', `\`${data.scoreStats}\``, true)
                    .addField('Source', `\`${data.source}\``, true)
                    .addField('Synonyms', `\`${data.synonyms}\``, true)
                    .addField('Status', `\`${data.status}\``, true)
                    .addField('Identifier', `\`${data.id}\``, true)
                    .addField('Link', data.url, true)
                    .setTimestamp()
                    .setFooter({text: `Requested by ${interaction.user.tag}`, iconURL: interaction.user.displayAvatarURL({ dynamic: true })})
                interaction.reply({embeds: [malEmbed]})
            }
        )
    }
}